CREATE TABLE TAREAS (
    ID_TAREA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DESCRIPCION VARCHAR (30) NOT NULL, 
    ESTADO VARCHAR (15) NOT NULL DEFAULT 'TO DO',
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_TAREA),
    CONSTRAINT chk_Estado CHECK (ESTADO IN ('TO DO', 'IN PROGRESS', 'DONE')),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

CREATE TABLE USUARIOS(
ID_USUARIO INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NOMBRE VARCHAR(30) NOT NULL, 
EMAIL VARCHAR(30) NOT NULL UNIQUE, 
PASSWORD VARCHAR(30) NOT NULL,
PRIMARY KEY (ID_USUARIO)
);

drop table USUARIOS

INSERT INTO TAREAS (DESCRIPCION, ESTADO, ID_USUARIO)
VALUES ('Crear BD', 'TO DO', 1 ),
('Cambiar Estados', 'TO DO', 1), 
('Crear Diseño', 'IN PROGRESS', 1), 
('Recibir Datos', 'DONE' ,2), 
('Eliminar Tareas', 'DONE', 2); 

INSERT INTO USUARIOS (NOMBRE, EMAIL, PASSWORD)
VALUES ('Johanna', 'simbrecht@birt.eus', '77777c'),
    ('Sindy', 'jimbrecht15@hotmail.com', '77777c'),
    ('Paola', 'gini.pao@gmail.com', '77777c');
